#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// Include the header file generated by javac (use javah or javac with -h option to generate this)
#include "com_dashboard_SystemInfoJNI.h"

// Function to get CPU usage by reading /proc/stat
JNIEXPORT jfloat JNICALL Java_com_dashboard_SystemInfoJNI_getCpuUsage(JNIEnv *env, jobject obj) {
    FILE *file;
    char line[256];
    unsigned long long user, nice, system, idle, iowait, irq, softirq, steal, total, total_idle;
    float cpu_usage = 0.0f;

    // Open the /proc/stat file to get CPU stats
    file = fopen("/proc/stat", "r");
    if (file == NULL) {
        perror("fopen");
        return 0.0f;
    }

    // Read the first line containing CPU statistics
    fgets(line, sizeof(line), file);
    sscanf(line, "cpu %llu %llu %llu %llu %llu %llu %llu %llu",
           &user, &nice, &system, &idle, &iowait, &irq, &softirq, &steal);

    total = user + nice + system + idle + iowait + irq + softirq + steal;
    total_idle = idle + iowait;

    cpu_usage = 1.0f - (float)total_idle / total;

    fclose(file);
    return cpu_usage;
}

// Function to get total memory by reading /proc/meminfo
JNIEXPORT jlong JNICALL Java_com_dashboard_SystemInfoJNI_getTotalMemory(JNIEnv *env, jobject obj) {
    FILE *file;
    char line[256];
    long total_memory = 0;

    // Open the /proc/meminfo file to get memory info
    file = fopen("/proc/meminfo", "r");
    if (file == NULL) {
        perror("fopen");
        return 0;
    }

    // Read the first line containing total memory
    while (fgets(line, sizeof(line), file)) {
        if (strncmp(line, "MemTotal:", 9) == 0) {
            sscanf(line, "MemTotal: %ld kB", &total_memory);
            break;
        }
    }

    fclose(file);
    return total_memory;  // Return total memory in kilobytes (kB)
}
